#!/bin/bash
############################################################################
############################################################################
##
## Copyright 2019 International Business Machines
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE#2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions AND
## limitations under the License.
##
############################################################################
############################################################################
#
DIR="$(cd "$(dirname $0)" && pwd)"

ocacceldir=$DIR/..
PATH=$ocacceldir:$PATH

ocaccel_config=$ocacceldir/\.ocaccel_config

simulator=`grep SIMULATOR $ocaccel_config|cut -d = -f 2 |tr -d '"'`

cd $ocacceldir/hardware/sim
if [ $simulator == "xsim" ]; then
  if [ -d "xsim" ]; then
    xsim -gui xsim/latest/top_wrapper.wdb -view debug3_action_gmem_ddr4.wcfg
  else
    echo "Please launch a simulation (make sim) prior to see traces"
  fi
fi
if [ $simulator == "irun" ]; then
  if [ -d "ies" ]; then
    simvision -wave -input ./debug3_action_gmem_ddr4.svwf ./ies/latest/capiWave.shm
  else
    echo "Please launch a simulation (make sim) prior to see traces"
  fi
fi

cd ../..
