#!/bin/bash
#
# Copyright 2017 International Business Machines
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version=1.0
program=$(basename "$0")
prgdir=$(dirname $(readlink -f "$BASH_SOURCE")) # path containing this script
snap_root=$(dirname "$prgdir")

# output formatting
bold=$(tput bold)
normal=$(tput sgr0)

# Name of global config file
build_dir="$prgdir/build"
kconfig="$prgdir/Kconfig"
config="$build_dir/config"
snap_config="$snap_root/.snap_config"
snap_config_sh="$snap_config".sh
snap_config_cflags="$snap_config".cflags
autoconf=$snap_root/software/include/autoconf.h
option=menuconfig

# Print usage message helper function
function usage() {
  echo  "Usage: ${program} [OPTIONS]"
  echo  "    [-o <oldconfig/menuconfig/...>] Use this as option."
  echo  "    [-c <config>]        Copy results to this config file."
  echo  "    [-a <autoconf>]    Location of autoconf.h."
  echo  "    [-V] Print program version (${version})"
  echo  "    [-h] Print this help message."
  echo  "    <path-to-bit-file>"
  echo
  echo  "Utility to generate vivado_hls tcl configuration file."
  echo
}

# Parse any options given on the command line
while getopts ":a:o:c:Vh" opt; do
  case ${opt} in
      a)
      autoconf=$OPTARG
      ;;
      o)
      option=$OPTARG
      ;;
      c)
      snap_config=$OPTARG
      snap_config_sh=$OPTARG.sh
      snap_config_cflags=$OPTARG.cflags
      ;;
      V)
      echo  "${version}" >/dev/null
      exit 0
      ;;
      h)
      usage;
      exit 0
      ;;
      \?)
      printf "${bold}ERROR:${normal} Invalid option: -${OPTARG}\n"
      exit 1
      ;;
      :)
      printf "${bold}ERROR:${normal} Option -$OPTARG requires an argument.\n"
      exit 1
      ;;
  esac
done

echo  "SNAP Build Options" >/dev/null
echo  "  Kconfig:          $kconfig" >/dev/null
echo  "  Build directory:  $build_dir" >/dev/null
echo  "  config:           $snap_config" >/dev/null
echo  "  autoconf:         $autoconf" >/dev/null

if [ ! -e $build_dir ]; then
  echo  "Cloning kconfig from github.com/guillon/kconfig into $build_dir" >/dev/null
  git clone https://github.com/guillon/kconfig $build_dir
  if [ $? != 0 ]; then
      printf "FAILED: git clone https://github.com/guillon/kconfig $build_dir"
      exit 1
  fi
fi
if [ -e $snap_config ]; then
  cp -p $snap_config $config
else
  rm -f $config
fi

cmd="make -C $build_dir -f GNUmakefile TOPDIR=. SRCDIR=. KBUILD_KCONFIG=$kconfig $option"

echo  "Executing:" >/dev/null
echo  "  $cmd" >/dev/null
$cmd 2>/dev/null

if [[ $? != 0 ]]; then
    echo "Make kconfig failed!"
    exit 1
fi

echo  "Generating SNAP config files $snap_config, $snap_config_sh and $snap_config_cflags ..."
cp $config $snap_config
cat $snap_config | sed 's/^\([^#].*\)/export \1/' | tr -d '"' > $snap_config_sh
chmod +x $snap_config_sh
cat $snap_config | tr -d '"' | sed 's/^\([^#].*\)/SNAP_CFLAGS += "-DCONFIG_\1"/' > $snap_config_cflags

#add HBM interfaces management
hbm_axi_if_num=`cat $config |grep -i "HBM_AXI_IF_NUM"|cut -d'=' -f2`
for ((i=0; i<$hbm_axi_if_num; i++))
do
   echo "export HBM_AXI_IF_P$i=TRUE" >> $snap_config_sh
   echo "SNAP_CFLAGS += \"-DCONFIG_HBM_AXI_IF_P$i=TRUE\"" >> $snap_config_cflags
done

#Add Vivado release
#Starting with Vivado 2020.1 ethernet emac IP has a different pinout
ethernet_used=`grep ETHERNET_USED $snap_config|grep TRUE`
Vivado_Major_release=`vivado -version |grep Vivado| cut -d'.' -f1|tr -d "Vivado "`
if [ $Vivado_Major_release -gt 2019 ] && [ $ethernet_used != "" ]; then
      echo "export ENABLE_EMAC_V3_1=TRUE" >> $snap_config_sh
      echo "SNAP_CFLAGS += \"-DCONFIG_ENABLE_EMAC_V3_1=TRUE\"" >> $snap_config_cflags
fi

#Starting with Vivado 2020.2 vivado_hls is replaced by vitis_hls
hls_support=`grep HLS_SUPPORT $snap_config|grep TRUE`
Vivado_Major_release=`vivado -version |grep Vivado| cut -d'(' -f1|tr -d "Vivado "|cut -d '.' -f1`
Vivado_Minor_release=`vivado -version |grep Vivado| cut -d'(' -f1|tr -d "Vivado "|cut -d '.' -f2`
if [ $Vivado_Major_release -ge 2020 ] && [ $hls_support != "" ]; then
  if [ $Vivado_Minor_release -gt 1 ]; then
      echo "export HLS_VITIS_USED=TRUE" >> $snap_config_sh
      echo "SNAP_CFLAGS += \"-DCONFIG_HLS_VITIS_USED=TRUE\"" >> $snap_config_cflags
  fi
fi

echo  "Generation of SNAP config files done."
echo

if [ -f $build_dir/include/linux/autoconf.h ]; then
  echo  "Copy resulting $autoconf file ..."
  cp $build_dir/include/linux/autoconf.h $autoconf
fi
